### ISSUE TITLE
Support for Better Advancements

### ISSUE THREAD

**Issue by Mcboyo** [ScottKillen/Nellik-s-HighDef-GUIs#14]
* **Mod name:** *Better Advancements*
  * **Mod url:** *https://minecraft.curseforge.com/projects/better-advancements*
  * **Minecraft version:** *1.12.2*

#### Description or Reason for Nomination
It has amassed a total of 6 million downloads and is the successor to BetterAchievements, which is currently supported by Nelik's GUI.

**Comment by ScottKillen** [comment]
This will be in the next release.

Thanks!
