### ISSUE TITLE
JEI GUIs Not Functioning (File Names Changed)

### ISSUE THREAD

**Issue by CMYKMatter** [ScottKillen/Nellik-s-HighDef-GUIs#16]
- [x] **Bug**

  * **Minecraft version:** *1.12.2*
  * **Involved mods (if any):** *JEI & JER*

JEI and JER interface in 1.12.2 seems to go back to default though other GUIs are functioning fine. Same problem with no other resource packs enabled besides this one.

**Comment by ScottKillen** [comment]
Please post a screenshot. You can drag it and drop it in a comment.

**Comment by CMYKMatter** [comment]
Sure thing.  This is on a fresh install of 1.12.2 with the only mod installed being JEI. The only resource pack installed is the GUI.  The creative interface and all others work fine from what I can tell: 

![nellikscreative](https://user-images.githubusercontent.com/53919192/62808356-d8cabe00-bac5-11e9-85ec-28074daa102f.png)

It's only when I click on an JEI recipe that I see the default UI

![nelliks](https://user-images.githubusercontent.com/53919192/62808384-ea13ca80-bac5-11e9-8b5e-de59d34133f7.png)

Let me know if that helps at all and any additional details you may need.

**Comment by CMYKMatter** [comment]
So I took a look over at JEI's page and it does seem that at some point they changed the naming and structure of their textures.

https://github.com/mezz/JustEnoughItems/tree/1.12/src/main/resources/assets/jei/textures/gui

Not sure if that helps, but seems like they broke a lot of things up.

**Comment by ScottKillen** [comment]
@CMYKMatter Thanks for this...It does look like they have made some changes. I will  work on this.

**Comment by CMYKMatter** [comment]
@ScottKillen Awesome. Thanks for that. Love the pack and all the work you've done on it.
