### ISSUE TITLE
Refined Storage Support

### ISSUE THREAD

**Issue by AveriAeterna** [ScottKillen/Nellik-s-HighDef-GUIs#17]
Refined Storage for 1.12.2
https://www.curseforge.com/minecraft/mc-mods/refined-storage

Refined Storage is a popular storage mod for modded Minecraft. It is similar but simpler than Applied Engergistics 2.  It basically adds a unified storage system that can be easily expanded upon and accessed.

**Comment by ScottKillen** [comment]
This has been added to v2.7
