### ISSUE TITLE
Rustic Support

### ISSUE THREAD

**Issue by DocSloe** [ScottKillen/Nellik-s-HighDef-GUIs#19]
Rustic
https://www.curseforge.com/minecraft/mc-mods/rustic
Minecraft 1.12.2

G'day! Not a high priority issue, but I really like the way your texture pack makes my modpack shine! Just a lil issue with how Rustic containers and alchemy don't want to play nicely with your lovely textures.  Let me know if integrating it isn't a bother/possible.
![eg1](https://user-images.githubusercontent.com/63194704/78499541-a1b3c600-7794-11ea-958e-78065a761556.png)
![eg2](https://user-images.githubusercontent.com/63194704/78499543-a37d8980-7794-11ea-8440-bbb1ad39203f.png)

**Comment by ScottKillen** [comment]
Thanks for the kind words!

This should not be an issue. 

What mod pack are you using?

**Comment by DocSloe** [comment]
Hi Scott! Thanks for the quick reply!

I'm using my own custom modpack linked here~ https://www.curseforge.com/minecraft/modpacks/sloecraft

I just noted that there could be a small issue with how the mod 'LeatherWorks' in the pack renders the player's inventory when opening leather trunks or knapsacks. I can open another issue for that later, when we're done with this one?

**Comment by ScottKillen** [comment]
@DocSloe All done.

BTW, What texture pack are you using?
