### ISSUE TITLE
wrong version download 1.7.10

### ISSUE THREAD

**Issue by laboblox** [ScottKillen/Nellik-s-HighDef-GUIs#3]
https://minecraft.curseforge.com/projects/nelliks-highdef-guis/files/2514204
downloading the 1.7.10 version results in downloading 1.12

**Comment by ScottKillen** [comment]
It is a problem with the curse interface...pressing the green "Download" button downloads the latest (1.12) button. Try pressing the gray "Download" button on the same page. :cowboy_hat_face:
