### ISSUE TITLE
CoFH Mods

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [ScottKillen/Nellik-s-HighDef-GUIs#5]
- [x] **Mod Nomination**

  **Mods names:** *Thermal Expantion, Thermal Dynamics, Thermal Foundation.*
  **Mods URLs:** 
    * [Thermal Dynamics](https://minecraft.curseforge.com/projects/thermal-dynamics?gameCategorySlug=mc-mods&projectID=227443) 
    *  [Thermal Foundation](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation)  
    *  [Thermal Expansion](https://minecraft.curseforge.com/projects/thermalexpansion?gameCategorySlug=mc-mods&projectID=69163)
* **Versions:** *Almost Any*

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
In 1.4.2 It Was Only Thermal Expansion, Then Expanded By  Thermal Foundation (That Thermal Expansion And Thermal Dynamics Needs It And All Of Them Need For Themselves CoFH Core And This One Do Not Have GUIs)
 And Then Added Thermal Dynamics  Witch Added Cover And Improved Ducts

**Comment by ScottKillen** [comment]
Included in #11

**Comment by ScottKillen** [comment]
These mods have been completed in the latest [downloads](https://minecraft.curseforge.com/projects/nelliks-highdef-guis).
