### ISSUE TITLE
JEI changed file names or something?

### ISSUE THREAD

**Issue by fivestang** [ScottKillen/Nellik-s-HighDef-GUIs#7]
- [x] **Bug**

  * **Minecraft version:** *1.12.2*
  * **Involved mods (if any):** *JEI v4.13.1.220*

#### Description or Reason for Nomination

JEI seems to have changed their gui file name and format or something?  Copying recipe_background.png to recipe_background_2.png sort of gets it working again.

**Comment by ScottKillen** [comment]
I'll investigate
